INSERT INTO "PUBLIC"."TB_WALLET_TYPE" ("ID", "DESCRIPTION") VALUES (1, 'user');
INSERT INTO "PUBLIC"."TB_WALLET_TYPE" ("ID", "DESCRIPTION") VALUES (2, 'merchant');

INSERT INTO "PUBLIC"."TB_WALLET"("BALANCE","CPF_CNPJ","EMAIL","FULL_NAME","PASSWORD","WALLET_TYPE_ID") VALUES ('50.0', '111.111.111-11', 'bob@gmail.com', 'Bob Brown', '123', 1);
INSERT INTO "PUBLIC"."TB_WALLET"("BALANCE","CPF_CNPJ","EMAIL","FULL_NAME","PASSWORD","WALLET_TYPE_ID") VALUES ('50.0', '222.222.222-22', 'maria@gmail.com', 'Maria Brown', '123', 2);